apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: host.docker.internal:5433
    user: factory
    secureJsonData:
      password: factory
    jsonData:
      database: factory
      sslmode: disable
      maxOpenConns: 10
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
