apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: bfgm9zpuen20wa
    type: postgres
    url: timescaledb:5432
    user: factory
    secureJsonData:
      password: factory
    jsonData:
      database: factory
      sslmode: disable
      maxOpenConns: 10
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
